### PR TITLE
Stair improvement

### PR DESCRIPTION
**Pull request by ingolvjr**
Added colliders to the stairs to make getting up and down faster

I don't know what happened with all the textmesh files, but git wouldn't let me discard any supposed changes, but It looks like it still works fine

### CODE REVIEW

**Comment by ingolvjr** [comment]
Closes #191

**Review by eamathie — CHANGES_REQUESTED** [review]
The player is still required to snipe a step on the staircase, so the issue of difficult aiming still exists. I previously made a mesh which can be used for this purpose, which covers the staircase in a slope. It is called building2_stairs_collider, and is located at Assets/FishFeeding/Components/Office/Models/building2_stairs_collider.fbx:

image
Just disable the mesh renderer and use a mesh collider. There's also a variant that blocks the area in front of the window to prevent clipping through the bottom of the staircase.

Another problem is that if the player teleports onto a step a bit too high, they get teleported to the first floor despite already being on the first floor (and vice versa). Perhaps a system where a big collider on the first and second floor respectively in front of the staircase tells the "system" which floor the player is currently on would work? Then the player can teleport anywhere on the staircase and still end up on the correct floor. 

Another problem is that the player can teleport onto the first and last step without teleporting.

**Review by qlpham231 — CHANGES_REQUESTED** [review]
Similar feedback as mentioned above

**Comment by ingolvjr** [comment]
Could you elaborate on the last step? Do you think it's a result of my changes or a preexisting issue?

**Comment by eamathie** [comment]
The player can teleport onto the staircase without getting teleported to the other floor. This is possible by teleporting onto the lowermost or topmost steps of the stairs. The player is teleported if they lean forward, so it is possible that the colliders are a little too small. They do not look to small visually though.

**Review by qlpham231 — APPROVED** [review]

**Review by eamathie — APPROVED** [review]

**Pull request merged**
