### PR TITLE
feat: new knife spawn after second knife get discarded

### PR DESCRIPTION
**Pull request by Herman1412**
when a backup knife gets discarded a new on will respawn in the same location

close: #514

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
once the backup knife is discarded no new knife appears

* **What is the new behavior?** (if this is a feature change)
when discarding a backup knife, a new one will spawn

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

### CODE REVIEW

**Review by qlpham231 — CHANGES_REQUESTED** [review]
After making the first knife chip, the knife doesn't change to the chipped knife but the second knife on the table changes to a chipped knife instead.

**Review by eamathie — CHANGES_REQUESTED** [review]
There are big flying red text in the HSE room when running a build.

**Review by qlpham231 — APPROVED** [review]
The correct knife becomes chipped but the user should maybe get an "incorrect" sound when cutting fish with the chipped knife. The new knife that gets spawned does also not have a random durability but is set to 5 each time. However, it's important to get the respawn fix in develop quickly so the user doesn't get stuck to publish the app, so I'll approve this and create issues for these.

**Review by qlpham231 — CHANGES_REQUESTED** [review]
Saw now that the newest from develop needs to be pulled and changes to the bleeding scene added afterwards.

**Review by qlpham231 — APPROVED** [review]

**Pull request merged**
