### PR TITLE
Ff improve qa layout

### PR DESCRIPTION
**Pull request by mefriis**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
#436 

* **What is the new behavior?** (if this is a feature change)
Feature new room structures: roof and walls
Fix placements of objects and fish spawning/despawning
Edited conveyor rolling texture to match speed of fish
Added lamps to roof

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Review by jonp-h — COMMENTED** [review]
Looks good. The intersection above the gutting station (where the fish should come from) should be replaced with a box/device that despawns fish from sorting station and spawns new fish for the gutting station when the gutting station is activated. Could this PR also implement that? Should go under "fix intersection" task.

**Comment by mefriis** [comment]
> Looks good. The intersection above the gutting station (where the fish should come from) should be replaced with a box/device that despawns fish from sorting station and spawns new fish for the gutting station when the gutting station is activated. Could this PR also implement that? Should go under "fix intersection" task.

There is a despawner and spawner in the "LightningBox". The fish goes from the two sorting stations, onto the long conveyor down the slide and then despawns. New fish spawns in the "LigthningBox" once the gutting sorting task is started. This can be done with some other "box" of course.

**Comment by jonp-h** [comment]
> > Looks good. The intersection above the gutting station (where the fish should come from) should be replaced with a box/device that despawns fish from sorting station and spawns new fish for the gutting station when the gutting station is activated. Could this PR also implement that? Should go under "fix intersection" task.
> 
> 
> 
> There is a despawner and spawner in the "LightningBox". The fish goes from the two sorting stations, onto the long conveyor down the slide and then despawns. New fish spawns in the "LigthningBox" once the gutting sorting task is started. This can be done with some other "box" of course.

Would it make more sense to see the fish enter the gutting box instead of spawning within it?

**Comment by mefriis** [comment]
> > > Looks good. The intersection above the gutting station (where the fish should come from) should be replaced with a box/device that despawns fish from sorting station and spawns new fish for the gutting station when the gutting station is activated. Could this PR also implement that? Should go under "fix intersection" task.
> > 
> > 
> > There is a despawner and spawner in the "LightningBox". The fish goes from the two sorting stations, onto the long conveyor down the slide and then despawns. New fish spawns in the "LigthningBox" once the gutting sorting task is started. This can be done with some other "box" of course.
> 
> Would it make more sense to see the fish enter the gutting box instead of spawning within it?

Good point. I will make a despawn/spawn functionality before the gutting box.

**Comment by jonp-h** [comment]
> > Looks good. The intersection above the gutting station (where the fish should come from) should be replaced with a box/device that despawns fish from sorting station and spawns new fish for the gutting station when the gutting station is activated. Could this PR also implement that? Should go under "fix intersection" task.
> 
> 
> 
> There is a despawner and spawner in the "LightningBox". The fish goes from the two sorting stations, onto the long conveyor down the slide and then despawns. New fish spawns in the "LigthningBox" once the gutting sorting task is started. This can be done with some other "box" of course.

Edit: I think I understand what you mean now. If there is fish going into the gutting machine then the PR is good to merge :)

**Comment by mefriis** [comment]
> > > Looks good. The intersection above the gutting station (where the fish should come from) should be replaced with a box/device that despawns fish from sorting station and spawns new fish for the gutting station when the gutting station is activated. Could this PR also implement that? Should go under "fix intersection" task.
> > 
> > 
> > There is a despawner and spawner in the "LightningBox". The fish goes from the two sorting stations, onto the long conveyor down the slide and then despawns. New fish spawns in the "LigthningBox" once the gutting sorting task is started. This can be done with some other "box" of course.
> 
> Edit: I think I understand what you mean now. If there is fish going into the gutting machine then the PR is good to merge :)

Fish from the two grading machines are gathered on one conveyor, and then they slide off into the gutting machine where they despawn as they enter. New fish spawn in the machine when the gutting sorting task starts.

**Pull request merged**
