### PR TITLE
fix: fixed the A button so it starts the game #181

### LINKED ISSUE #181: FishFeed task not working
the sign says "Press 'A' to start" but this does not currently work

### PR DESCRIPTION
**Pull request by qlpham231**
Closes #181 

Changed how we access the 'A' button from the controller in the Game-script and instead uses VRIF Default Input Actions. 
To get this new change you need the updated VRIF Default Input Actions file from me since the change is gitignored.

### CODE REVIEW

**Comment by qlpham231** [comment]
@SnorreForbregd Could you build FishFeeding with my new changes and check if the 'A' button works now? I have sent you a unity package with the required change mentioned above.

**Comment by ingolvjr** [comment]
@qlpham231 I think you should be able to make a separate input map and use both simultaneously

**Comment by qlpham231** [comment]
@ingolvjr Could you explain more of what you mean?

**Comment by ingolvjr** [comment]
Unitys new input system uses input maps, you can enable/disable input maps at runtime. We could make a separate one for VR4VET/blue-sector with the 'A' button input and use it alongside the BNG map, that way it can be commited nad pushed to the repo

**Comment by qlpham231** [comment]
I can look into that after Snorre is able to confirm that my new changes work in the build

**Comment by qlpham231** [comment]
Pull request #213 solves this issue and we therefore don't need to implement these changes

**Pull request closed without merging**
