### PR TITLE
Removed Grabbable Script, Fixed tooltip script ref

### PR DESCRIPTION
**Pull request by SnorreForbregd**
Branch containing fixes to issue #187 and #188

- Removed grabbable script from all MerdButtonRound Prefabs
- Removed reference to the unused ChangeMerdHint from InnerButton OnButtonDown Event
- Added reference to the Deactivate function of the SimpleTooltip attached to the used ChangeMerdHint to the InnerButton OnButtonDown Event
  - This is how it is done with the other hint tooltips.
  - Yes, there are two ChangeMerdHint objects in the hierarchy. One is used, the other is not.

### CODE REVIEW

**Comment by ingolvjr** [comment]
Looks good to me!

**Comment by eamathie** [comment]
Looks good. The tooltip still behaves strangely, but I think this is probably related to the built-in time delay

**Review by qlpham231 — APPROVED** [review]
I'm not able to grab the merd buttons so that is issue is solved.
I'm able to close the tooltips after interacting with the referenced object, but it is still not optimal since the hints appear after a delay which makes them not closable if the user solves the issue before the tooltip appears. So if the user solves the issue before the tooltip appears then they won't be able to close the the tooltip by doing the correct action. 
This however could be a new issue instead.

**Comment by fominykh** [comment]
@SnorreForbregd @qlpham231 Are we talking a second or two? Do you think we can make the tooltip delay customizable and set it to 0 in the Fish Feed task?

**Comment by SnorreForbregd** [comment]
The delays are done in the code, I have no idea why they are there

**Comment by SnorreForbregd** [comment]
Regarding the tooltips being unclosable if the specified action is done beforehand, I don't understand how that would be the case. The way it is currently set, whenever an action is done that would close a tooltip, it calls the function to close that tooltip regardless of whether it is opened or closed, and regardless of any other factors

**Comment by SnorreForbregd** [comment]
Added a commit that removes the delay. Was previously set to be random between 10 and 60 seconds of delay

**Review by ingolvjr — APPROVED** [review]
Finally found the 'approve' button, but yeah, this looks good, does what the description says it should

**Review by eamathie — COMMENTED** [review]
I a couple of issues:
- The hints only appeared once when playing. In other words, when a certain hint (for example the "fish is full"-hint) is shown, it will never appear again, even if the player is wasting food.
- The recap tooltip that appears at the end of the tutorial is triggered when grabbing the screen, not when releasing. This is a problem, because it lasts for a set period of time, possibly not giving the player enough time to read it after exiting immersive view.

Me and Lan are familiar with how this is setup, so we're gonna look at it.

**Review by qlpham231 — CHANGES_REQUESTED** [review]
Fixed the TaskRecapHint to show on release. 
The other issue with the full and hungry hints, I don't think the tooltips are activated again after being deactivated when the user touches the referenced object. Perhaps @SnorreForbregd should look at that?

**Pull request merged**
