### PR TITLE
Add tablet to FishFeeding

### LINKED ISSUE #177: Get Tablet to FishFeed

### PR DESCRIPTION
**Pull request by qlpham231**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature: Adds the tablet prefab to the FishFeeding scene and created ScoreTablet.cs to evaluate the fish feeding task for tablet.

* **What is the current behavior?** (You can also link to an open issue here)
No tablet in Fishfeeding. Closes #177, #178

* **What is the new behavior?** (if this is a feature change)
There is a tablet in the left holster of the player and shows the task fish feeding task and its subtasks. While playing the task the player should be able to trigger the completion of subtasks by steering the camera with the joystick, changing feeding intensity for the current cage and pressing a fish cage button. ScoreTablet.cs calculates the score at the end but the UI for this is not done yet.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
By importing the tablet, FishWelfare that used to use the old tablet creates a lot of yellow errors since it is trying to access files that don't exist anymore. However, both FishWelfare and FishFeeding scenes still works.

* **Other information**:
The UI for score, score to each skill and for showing the completion of the fish feeding task does not work. 
Showing the completion of the subtasks does not work in the build in addition to previously mentioned issues.
The editor uses the right hand when clicking on the tablet and in the build the left hand is used.
<br />

**Additional new changes:**  
- Added new fix for Tablet from VR4VET and shows the score page with table, but it doesn't show the updated score values.
- The skills page shows "0/100"-scores but doesn't show updated score value.
- The checkmarks for each subtasks should be completed after finishing them in the build now

### CODE REVIEW

**Review by ingolvjr — CHANGES_REQUESTED** [review]
The tablet works, but all the placeholders are still there, making it confusing to actually find what 's actually in use. and the tablet UI is drawn over the UI pointer, making it hard to see exactly what you're pointing at, it also goes right through the tablet, this is very confusing

**Review by eamathie — CHANGES_REQUESTED** [review]
Score does not appear on the right hand monitor after game is completed in builds. Works after commenting out tablet.GiveFinalTabletScore() in Game.cs line 141. Probably something in that function.

**Comment by qlpham231** [comment]
Fixed the previously mentioned issues and added new fix for Tablet from VR4VET. The placeholders should have been gone now, @ingolvjr check if you have the same version of the Tablet Adapted.prefab.
Discovered new bug where the hologram camera doesn't update to new fish cage camera when playing the game in build, @eamathie could you help me there?

**Review by eamathie — APPROVED** [review]
Tested. Everything works as intended as far as the current tablet allows, and previous bugs are fixed.

**Review by ingolvjr — APPROVED** [review]
Yep, works as well as the current prefab allows

**Review by SnorreForbregd — APPROVED** [review]

**Pull request merged**
