### PR TITLE
Ff change folder structure

### PR DESCRIPTION
**Pull request by jonp-h**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Restructures the folder structure within the Fish Factory project.

* **What is the current behavior?** (You can also link to an open issue here)
Inconsistencies within the fish factory folder structure

* **What is the new behavior?** (if this is a feature change)
Improved folder structure

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Yes. Almost all files have changed locations, and as such new files created after the branch must be moved to the correct folder.

* **Other information**:
No

### CODE REVIEW

**Comment by mefriis** [comment]
Merge conflicts?

**Comment by jonp-h** [comment]
> Merge conflicts?

I get 801 _empty_ merge conflicts, do you see any conflicting files @mefriis ?

**Comment by mefriis** [comment]
> > Merge conflicts?
> 
> I get 801 _empty_ merge conflicts, do you see any conflicting files @mefriis ? I'm asking because I'm confused..

I says:
Conflicting files
Assets/FishFactory/Scripts/CutFishBody.cs
Assets/FishFactory/Scripts/CutFishGill.cs
Assets/FishFactory/Scripts/SceneLogic/SceneController.cs

**Comment by MarkusJohansen** [comment]
I get the same conflicts as Mikkel. I would just suggest pulling local `fish-factory` into the branch with `git pull --rebase fish-factory`. If you are not familiar with the command, i suggest that you familiarize yourselves with it first.

There is also a significant difference in the amount of removed code vs additions - which i find peculiar. If we only restructured the project, the amounts should be about similar (if we just moved files). 

image

**Comment by MarkusJohansen** [comment]
> > > > Merge conflicts?
> > > 
> > > 
> > > I get 801 _empty_ merge conflicts, do you see any conflicting files @mefriis ? I'm asking because I'm confused..
> > 
> > 
> > I says: Conflicting files Assets/FishFactory/Scripts/CutFishBody.cs Assets/FishFactory/Scripts/CutFishGill.cs Assets/FishFactory/Scripts/SceneLogic/SceneController.cs
> 
> Strangely, none of these files are merge conflicts to me.. Channeling merge champion @MarkusJohansen

It seems like most of the files are meta files - maybe this is the reason for your conflicts? I only get three conflicts just like Mikkel.

**Review by MarkusJohansen — CHANGES_REQUESTED** [review]
Se comments. Especially regarding the difference between removals and additions

image

**Comment by jonp-h** [comment]
> > > > > Merge conflicts?
> 
> > > > 
> 
> > > > 
> 
> > > > I get 801 _empty_ merge conflicts, do you see any conflicting files @mefriis ? I'm asking because I'm confused..
> 
> > > 
> 
> > > 
> 
> > > I says: Conflicting files Assets/FishFactory/Scripts/CutFishBody.cs Assets/FishFactory/Scripts/CutFishGill.cs Assets/FishFactory/Scripts/SceneLogic/SceneController.cs
> 
> > 
> 
> > Strangely, none of these files are merge conflicts to me.. Channeling merge champion @MarkusJohansen
> 
> 
> 
> It seems like most of the files are meta files - maybe this is the reason for your conflicts? I only get three conflicts just like Mikkel.
> 
> 

Highly likely that this is just meta files yes, however I do not get the conflicting .cs files

**Pull request closed without merging**
